// This file generated by sqlaction v0.2.9.0

package cn.edu.zucc.personplan.dao;

import java.math.*;
import java.util.*;
import java.sql.Time;
import java.sql.Timestamp;
import java.sql.Connection;
import java.sql.Statement;
import java.sql.PreparedStatement;
import java.sql.ResultSet;

public class CarInfoSAU extends CarInfoSAO {

}
