// This file generated by sqlaction v0.2.9.0
// WARN : DON'T MODIFY THIS FILE

package cn.edu.zucc.personplan.dao;

import java.math.*;
import java.util.*;
import java.sql.Time;
import java.sql.Timestamp;
import java.sql.Connection;
import java.sql.Statement;
import java.sql.PreparedStatement;
import java.sql.ResultSet;

public class CarInfoSAO {

	int				carId ; // PRIMARY KEY
	int				netId ;
	int				typeId ;
	String			license ;
	int				carStatus ;

	int				_count_ ; // defining for 'SELECT COUNT(*)'

	// SELECT * FROM car_info
	public static int SELECT_ALL_FROM_car_info( Connection conn, List<CarInfoSAU> carInfoListForSelectOutput ) throws Exception {
		Statement stmt = conn.createStatement() ;
		ResultSet rs = stmt.executeQuery( "SELECT * FROM car_info" ) ;
		while( rs.next() ) {
			CarInfoSAU carInfo = new CarInfoSAU() ;
			carInfo.carId = rs.getInt( 1 ) ;
			carInfo.netId = rs.getInt( 2 ) ;
			carInfo.typeId = rs.getInt( 3 ) ;
			carInfo.license = rs.getString( 4 ) ;
			carInfo.carStatus = rs.getInt( 5 ) ;
			carInfoListForSelectOutput.add(carInfo) ;
		}
		rs.close();
		stmt.close();
		return carInfoListForSelectOutput.size();
	}

}
